### ISSUE TITLE
Add lhns to maintainer team

### ISSUE THREAD

**Issue by raboof** [sbt/sbt-sbom#102]
@lhns contributed some good features recently (https://github.com/sbt/sbt-sbom/pulls?q=is%3Apr+author%3Alhns+is%3Aclosed). 

@lhns: would you like to be added to the maintainer team for sbt-sbom?

**Comment by eed3si9n** [comment]
Invite sent - https://github.com/orgs/sbt/teams/sbt-bom/members

**Comment by lhns** [comment]
Thank you very much!
