### ISSUE TITLE
Support latest bom version

### ISSUE THREAD

**Issue by siculo** [sbt/sbt-sbom#17]
Actually, the latest version is 1.3.

**Comment by siculo** [comment]
All specs are available here:
https://cyclonedx.org/docs/1.0/xml/
https://cyclonedx.org/docs/1.1/xml/
...

**Comment by pjfanning** [comment]
Thanks @siculo for developing this plugin. Have you considered using https://github.com/CycloneDX/cyclonedx-core-java as a potentially easier way to keep up to date with the various sbom spec versions (1.4 is now the latest)?

**Comment by siculo** [comment]
> Thanks @siculo for developing this plugin. Have you considered using https://github.com/CycloneDX/cyclonedx-core-java as a potentially easier way to keep up to date with the various sbom spec versions (1.4 is now the latest)?

I am using it. I am working to support the latest versions of the spec. But I'm busy with my work and have little free time for the plugin. So progress is slow, sorry.
