### ISSUE TITLE
Add Hippocratic License to project

### ISSUE THREAD

**Issue by siculo** [sbt/sbt-sbom#52]
The project will be distribuited with both MIT license and Hippocratic License 3.0. Here is the customized HL3 that will be used: https://firstdonoharm.dev/build?modules=sv

**Comment by siculo** [comment]
No. It was my intention to add some ethical obligations to the users when this was a project under my responsibility and nobody was using it yet. But now it's a different scenario. So, better close the issue.

**Comment by mdedetrich** [comment]
Thanks, closing
