### ISSUE TITLE
Move to community maintenance

### ISSUE THREAD

**Issue by raboof** [sbt/sbt-sbom#60]
I talked to @siculo about the plans for ongoing maintenance of this project. He mentioned the best way forward is probably to fork the project and publish it under a different groupId. I'd be interested in getting that off the ground, and @mdedetrich would like to help with this as well.

@eed3si9n would you like to fork this project into `sbt/sbt-sbom` so we can continue there?

**Comment by raboof** [comment]
> I'd generally recommend transferring the repo, otherwise sending a PR would always default to this repo, but here it is - https://github.com/sbt/sbt-bom

Ah, that's a good point, thanks! Could you rename it to `sbt-sbom` to disambiguate it a bit better from the various plugins that are about the separate Maven Bill of Materials concept (e.g. https://github.com/heremaps/here-sbt-bom, https://github.com/lightbend/sbt-bill-of-materials)?

**Comment by raboof** [comment]
ah wait, I see the repo is now indeed 'forked' rather than 'transferred' - do I understand correctly that you'd recommend @siculo 'transfer' it instead? Is that still possible now or would it need the fork to be removed first?

**Comment by eed3si9n** [comment]
> do I understand correctly that you'd recommend @siculo 'transfer' it instead?

Yea.

> Is that still possible now or would it need the fork to be removed first?

We can try it, but I can always remove the fork.

**Comment by siculo** [comment]
I'm ok with transferring the repo. I've never done a transfer, so I'll have to look at the docs. I don't think it's complicated...

**Comment by siculo** [comment]
Who will take the ownership?

**Comment by eed3si9n** [comment]
You can transfer it to me @eed3si9n first, and I can re-transfer it to sbt and create a team with you and others in it.

**Comment by raboof** [comment]
> Another problem is to have others publish the same artifact on maven central. Maybe it's better to change group-id?

I think changing the group-id (to `com.github.sbt`? https://repo1.maven.org/maven2/com/github/sbt/ ) makes sense

**Comment by siculo** [comment]
> You can transfer it to me @eed3si9n first, and I can re-transfer it to sbt and create a team with you and others in it.

I have submitted the transfer request. You should receive a confirmation email.

**Comment by eed3si9n** [comment]
I've re-transferred it to sbt/sbt-sbom. Y'all can decide if this should be sbt-bom or sbt-sbom.

**Comment by eed3si9n** [comment]
@siculo There should be an invite to https://github.com/orgs/sbt/teams/sbt-bom in your inbox.

**Comment by mkurz** [comment]
> @siculo There should be an invite to https://github.com/orgs/sbt/teams/sbt-bom in your inbox.

@eed3si9n Would you mind adding me to that team as well? Thanks!

**Comment by siculo** [comment]
> @siculo There should be an invite to https://github.com/orgs/sbt/teams/sbt-bom in your inbox.

I don't see it. Can you check?

**Comment by eed3si9n** [comment]
@mkurz Done.

@siculo Yea. Here's a screenshot of pending invite:
<img width="478" alt="invite" src="https://github.com/user-attachments/assets/7f166c7b-ad4b-4be8-8499-39674a8c98c3">

**Comment by raboof** [comment]
I'm a member of the sbt-bom team but my review of #62 is still 'grey' - could it be the team hasn't been given write access to the transferred repo yet?

**Comment by mdedetrich** [comment]
Same here, I am just a member but not a maintainer

**Comment by raboof** [comment]
Looks good, thanks!

I guess we can keep this issue open until we've set things up to publish under `com.github.sbt:sbt-sbom`

**Comment by mdedetrich** [comment]
> Looks good, thanks!
> 
> I guess we can keep this issue open until we've set things up to publish under `com.github.sbt:sbt-sbom`

I plan to use sbt-github-actions for this unless someone has strong objections

**Comment by mdedetrich** [comment]
So I am going to close this issue as publishing is working (well at least the snapshot is), see https://github.com/sbt/sbt-sbom/actions/runs/11406505669/job/31740681174 .

If there are any more issues then we can open another ticket
