### ISSUE TITLE
Register project to Scala Steward

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-sbom#74]
@raboof @eed3si9n @mkurz Any objections?

**Comment by mdedetrich** [comment]
Likely blocked by https://github.com/sbt/sbt-sbom/pull/70

**Comment by raboof** [comment]
I'd say go for it! I don't think it needs to wait for #70

**Comment by mdedetrich** [comment]
PR made at https://github.com/VirtusLab/scala-steward-repos/pull/466

**Comment by mdedetrich** [comment]
Closing since linked PR is merged
